version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  web: &web
    build: .
    command: sh -c '
      bundle install;
      mkdir -p /app/tmp/pids;
      rm -rf /app/tmp/pids/*;
      bundle exec rails s -p 3000 -b "0.0.0.0"
      '
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      DB_URL: db
      DB_PASSWORD: password
      REDIS_URL: redis://redis
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3305
    tmpfs:
      - /tmp

  webpacker:
    <<: *web
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    command: sh -c '
      bundle install;
      ./bin/webpack-dev-server
      '
    depends_on:
      - web
    ports:
      - "3305:3305"

volumes:
  node_modules:
  rails_cache:
  packs:
  bundle:
    driver: local
